### ISSUE TITLE
Clarity on versioning

### ISSUE THREAD

**Issue by SapientGuardian** [operator-framework/operator-metering#1091]
It isn't clear what the current, finished, supported, and semantics of versions/releases are. 

https://github.com/operator-framework/operator-metering/releases shows the latest release to be 0.14.0 from last year, but my sense is that the "release-4.x branches" are more recent. I would have assumed that releases 4.0 through 4.5 were finished and actual releases, but I see 4.4 and 4.5 are identical and even with master, having received commits as recently as 8 hours ago.

I have some local customizations that I want to pin to a release version, but it seems like they're a moving target. Please advise (and ideally add some documentation) around this matter.

**Comment by timflannagan1** [comment]
We currently follow the Openshift release cycle since the 4.0 release and went GA in the 4.2 release. We're currently working on the 4.4 release cycle, which is why master/release-4.4/release-4.5 are all synced with the same commits. For more information about what has changed between releases, you would have to look at the OCP documentation. Here is the docset from the most recent release: https://docs.openshift.com/container-platform/4.3/metering/metering-about-metering.html

I realize this isn't ideal and I can help guide you attaching some changes to a release version.

**Comment by SapientGuardian** [comment]
Thanks for explaining, that makes sense!
