### ISSUE TITLE
promsum and awsBilling treated differently

### ISSUE THREAD

**Issue by devdattakulkarni** [operator-framework/operator-metering#282]
It seems that the two data sources - prometheus and aws billing - are handled in different manner currently.

According to the documentation promsum ReportDataSource is handled by using the ReportPrometheusQuery. But there is no such Query resource defined for handling awsbilling.

I was wondering if it would make sense to define something like ReportAWSBillingQuery for handling awsbilling ReportDataSource type.

**Comment by chancez** [comment]
They're treated differently by design, and the intent is that a ReportDataSource roughly maps to a table where data is accessible. With this in mind, I don't think we really want a new custom resource for each variation of this. Eventually we're likely to add a googleCloudBilling datasource, and datasources that support connecting to other database backends or systems, and all of these will just be a variation of the ReportDataSource. This is fairly similar to persistent volumes and the various volume plugins.
