### ISSUE TITLE
Adding another ReportDataSource CRD with an external Oracle importer

### ISSUE THREAD

**Issue by alinadonisa** [operator-framework/operator-metering#541]
Hi guys,

I am building a business case for using metering operator and I would like to know a couple of things:

1. If we would want to add information from Oracle for instance, is it possible to register another ReportDataSource CRD that would generate a PrestoTable CRD  and fill it with an external importer made by us without modifying the current code?  How can we add a custom importer in the current version? Is it possible to do this without fork?

2.  I've seen you chose to use the pull method to scrape data from Prometheus instead of push (remote_write). Is there a reason you did this? (just curious :) )

3. Do you have a slack channel or do you have a  meetup where people can join and ask questions?

Thanks,

**Comment by chancez** [comment]
1) This isn't possible today. We only support Hive currently and while we would like to support other backends in the future, we're currently focused on other things. 
    - Additionally, oracle isn't a connector supported by Presto today, so even if we did, as you mentioned you would likely need to import the data into Hive like we have to do with Prometheus metrics today.
    - Importing data is something we want to move away from generally, where possible, so this also complicates things. We will always have to support importing some data to support more use-cases, but I'd like it to be a little more flexible (be able to import things we don't support like in this case). *See my answer to your 2nd question below for more on this*.
    - The closest thing we could do to support something like this in the shorter term is to support referencing an existing table in the Presto Hive catalog as an unmanaged (external) table where we wouldn't directly interact with it, but could an existing table in Hive to as a reportDataSource that can be referenced. This would mean you could create the table in hive, copy the data into hive using presto or hive from oracle (however you choose, there's tools for it though), create a reportDataSource, and then access it like other reportDataSource tables. This is an idea I've had for a while, but it's on the backlog as we're focusing on other things for (stability, scaling, etc). 
    - You can the achieve the above solution somewhat today if you hardcode your manage the table/importing of data into it and hardcode the table names in your reportGenerationQuery to use that table you're manually managing. We can't guarantee a lot  in terms of supporting that though.

2) It requires changing Prometheus (config or otherwise), and we would prefer to not have to require any particular Prometheus configuration for the most part. We also don't want to be responsible for making Prometheus perform well on top of our storage layer (since the Prometheus storage layer is good at what it does). That said; we're looking at using the remote read API for metrics instead of the query API which will give us the raw metric data prometheus is scraping (the query API is giving us slightly averaged values).
    - Longer term than that, we also want to build a Presto connector for Prometheus to avoid having to import metric data into Hive. 
    - This could honestly be done at any point, but I'd also like to move any code that "imports" data into separate sub-projects which runs as a separate own pod/component from the reporting-operator (which is what does importing of metric data today). Along those lines, you could write your own code to handle importing your Oracle data into Hive. It could potentially even be a Kubernetes CronJob running [sqoop](https://sqoop.apache.org/) on a schedule.

3) Not really. You could ask questions to me in the kubernetes slack in the #kubernetes-operators channel though. I'm chancez on that slack as well.
