### ISSUE TITLE
Consolidated billing

### ISSUE THREAD

**Issue by jaxxstorm** [operator-framework/operator-metering#581]
The information on configuring operator metering with AWS Billing is quite sparse.

Does this work with consolidated billing at all?
Does the billing need to be in a specific format/directory layout? I see the schema file in the documentation, but it's not clear what it means.
Can this be configured without an S3 bucket, and calling the AWS billing API directly?

**Comment by chancez** [comment]
- Consolidated billing works. At the end of the day, it's just a cost and usage report in S3 that's used. Consolidated billing will produce reports containing information on all accounts under the billing account rather than just the single account's billing information.
- The directory format/layout expected is what the AWS cost and usage report outputs, you just need to specify the s3 bucket, and the path (prefix) used when creating the report.
- No, this only supports reading billing report data from S3. We are using Presto and Hive to present the underlying S3 bucket as a database table which we use in our queries.

I understand the documentation on this may be light, but are you looking for something specific? We provide an example metering configuration that just needs to be modified to use your values. Perhaps it would help if we showed what the configuration on the amazon side would look like to match up with the metering config?

**Comment by jaxxstorm** [comment]
This answered all the questions I had, thanks
