### ISSUE TITLE
allow set "reportingStart" to now

### ISSUE THREAD

**Issue by jaxxstorm** [operator-framework/operator-metering#641]
I just updated my installment, and noticed the changes which set reportingStart to be required.

I generate all of the reports via jsonnet - this leaves me with a couple undesirable options:

1 - Set the start time to a random date in the past and wait until the `ReportingPeriodWaiting` eventually catches up, which means for all new clusters a long period of time might pass
2 - Generate a valid RFC3389 date which will continuously mean by reports are being reapplied

Would it be possible to have a the `reportingStart` period be configurable to something like `now` which means it starts immediately? If we can get historical prometheus metrics configured then having the start time configurable is nice, but until then its just a delay in starting the report

**Comment by chancez** [comment]
1) This option will not work, as we now validate that reportingStart does not come before a period where data does not exist.
2) I don't really know what you mean here.

We changed the behavior because without requiring reportingStart, your first row of data will always be inaccurate since it will not contain a full periods worth of data.

The best alternative I can think of is that we could add a new option to the spec to allow for something similar to your request. We could use this option to change the behavior to calculate the status.nextReportTime based on the current time, if `spec.reportingStart` isn't set, and use status.nextReportTime when status.lastReportTime is unset (as is case for the first reportingPeriod) for the starting point. This would basically mean it would not run immediately, but would run at the first scheduled period after the current time.

Thoughts?

**Comment by chancez** [comment]
Actually, that might be something we can do by default without a new `spec` option. Ill discuss with the team.

**Comment by chancez** [comment]
I'll have a PR to change the behavior to default to using the current time to calculate the next period and use that as the starting point soon.

**Comment by jaxxstorm** [comment]
Awesome, that sounds perfect!
I can't really elaborate on 2) without going into a full spiel about our configuration mgmt tooling for Kubernetes, but it seems we have a solution already so awesome! thanks!

**Comment by jaxxstorm** [comment]
@chancez do we know when this will be available to use in a release? I'm having real problems getting reports working with the new reportingStart field for some reason :(

**Comment by pruan-rht** [comment]
@jaxxstorm, this PR has been superseded  by https://github.com/operator-framework/operator-metering/pull/643, which has been merged already.

**Comment by jaxxstorm** [comment]
@pruan-rht I saw it was already merged, I'm wondering how I can put it to use now? I'm using version 0.13.0 from the release repo as my reporting-operator docker image
