### ISSUE TITLE
Metering Operator container fails to start

### ISSUE THREAD

**Issue by dougjdouma** [operator-framework/operator-metering#741]
Image: quay.io/openshift/origin-metering-helm-operator:4.2. I see in the log Starting container process caused "exec: \"run-operator.sh\": executable file not found in $PATH"

**Comment by chancez** [comment]
We've stopped building this image for 4.2 because we've rewritten the operator as an ansible-operator. See the master branch for the manifests in https://github.com/operator-framework/operator-metering/blob/master/manifests/deploy/openshift/metering-ansible-operator/. Note that the `Metering` CRD was renamed to `MeteringConfig`.

If you wish to continue using the old version of things you may also checkout the release-4.1 branch and install from there.
