### ISSUE TITLE
Ansible Operator creating abandoned python child processes

### ISSUE THREAD

**Issue by dougjdouma** [operator-framework/operator-metering#744]
when deploying the ansible operator, we noticed a very high defunct child process rate caused by the ansible operator.

In just one minute of running, we had 16.  In running over a few hours, we were up to 700 and had to reboot the host

[root@rcos3m01 ~]# ps -ef|grep defunct |wc
    10      91     697
[root@rcos3m01 ~]# ps -ef|grep defunct |wc
    12     109     835
[root@rcos3m01 ~]# ps -ef|grep defunct |wc
    13     118     904
[root@rcos3m01 ~]# ps -ef|grep defunct |wc
    14     127     982
increasing pretty quickly
[root@rcos3m01 ~]# ps -ef|grep defunct |wc
    16     145    1111

**Comment by chancez** [comment]
Interesting. It seems to be all python processes and when I tested a barebones ansible-operator this doesn't seem to occur, so I'll investigate this today.

**Comment by chancez** [comment]
This is caused by our usage of async tasks in ansible, which double fork and don't get cleaned up due to not running a proper init.

I'm looking into running a proper init in the container so these processed get reaped, and also into not using async for these tasks since it doesn't seem to improve deploy speed much as it's currently implemented (after some recent refactoring the role doesn't really need async for making deploys run faster).
