### ISSUE TITLE
OCP 4.1: report terminates with status: false

### ISSUE THREAD

**Issue by rbaumgar** [operator-framework/operator-metering#755]
installed OpenShift 4.1 on aws
installed Metering 4.1.0 under namespace "metering"
all pods are running
```
$ oc get pod
NAME                                  READY     STATUS    RESTARTS   AGE
hdfs-datanode-0                       1/1       Running   0          3h31m
hdfs-namenode-0                       1/1       Running   0          3h31m
hive-metastore-0                      1/1       Running   0          3h31m
hive-server-0                         1/1       Running   0          3h31m
metering-operator-86df9dfb45-4spzp    2/2       Running   0          3h33m
presto-coordinator-7975b7c496-8lbwc   1/1       Running   0          3h31m
presto-worker-5d648dc685-hbrrk        1/1       Running   0          130m
reporting-operator-d474f6b85-zqgx4    1/1       Running   0          136m
```
create a report with
```
apiVersion: metering.openshift.io/v1alpha1
kind: Report
metadata:
  name: pod-memory-usage
spec:
  query: "pod-memory-usage"
  runImmediately: true
  reportingStart: '2019-01-01T00:00:00Z'
  reportingEnd: '2019-12-31T23:59:59Z'

$ oc get report pod-memory-usage -o json
...
    "status": {
        "conditions": [
            {
...
                "message": "Report has finished reporting. Report has reached the configured spec.reportingEnd: 2019-12-31 23:59:59 +0000 UTC",
                "reason": "Finished",
                "status": "False",
                "type": "Running"
...
```
So I can't find any reason for the failure!
The logfile of the report-operator shows following line
`time="2019-06-17T08:36:35Z" level=error msg="error queuing Report dependents of ReportDataSource cluster-cpu-capacity-raw" app=metering component=reportDataSourceWorker error="reportquery.metering.openshift.io \"unready-deployment-replicas\" not found" logID=GshSZSuRXM namespace=metering reportDataSource=cluster-cpu-capacity-raw`

any hint what's wrong?

**Comment by chancez** [comment]
The condition you see isn't a failure, it's expected behavior. It's indicating `Running: false" which means "not running", with reason "Finished", which would indicate it's reached the end of the reporting period as defined by `reportingEnd`. Since you've set `runImmediately`, this means the operator is not going to wait for the time periods to elapsed, but will instead run immediately without waiting for the data to exist nor the time period to have elapsed.

Set `spec.runImmediately` to `false` if you want it to wait for the scheduled periods to elapse before running queries.
