### ISSUE TITLE
the reporting-operator could not get information from API

### ISSUE THREAD

**Issue by jihed** [operator-framework/operator-metering#975]
I am deploying the latest image of the operator. When, I check the log on the reporting-operator pod I see that it could not get information from the api. Is there any specific role should added ? 

``E1011 12:58:08.637031       1 reflector.go:134] github.com/operator-framework/operator-metering/pkg/generated/informers/externalversions/factory.go:101: Failed to list *v1.HiveTable: the server could not find the requested resource (get hivetables.metering.openshift.io)
E1011 12:58:08.833365       1 reflector.go:134] github.com/operator-framework/operator-metering/pkg/generated/informers/externalversions/factory.go:101: Failed to list *v1.StorageLocation: the server could not find the requested resource (get storagelocations.metering.openshift.io)
E1011 12:58:09.038422       1 reflector.go:134] github.com/operator-framework/operator-metering/pkg/generated/informers/externalversions/factory.go:101: Failed to list *v1.Report: the server could not find the requested resource (get reports.metering.openshift.io)
E1011 12:58:09.238296       1 reflector.go:134] github.com/operator-framework/operator-metering/pkg/generated/informers/externalversions/factory.go:101: Failed to list *v1.ReportDataSource: the server could not find the requested resource (get reportdatasources.metering.openshift.io)
^C``

**Comment by chancez** [comment]
This indicates the CRDs aren't installed, which would mean the install script had errors or if you used an OLM based install, OLM didn't create the CRDs. This doesn't seem to be permissions related, but rather an error of existence. It's also possible you deleted the CRDs but the operator was still installed when it produced these logs.

Since we discussed using metering 4.2 instead of 4.1 over slack and had more success, I'm closing this.
